### ISSUE TITLE
Add support for shelly wave/qubino devices

### ISSUE THREAD

**Issue by 33Fraise33** [zwave-js/firmware-updates#95]
Hello,

it seems firmware for the shelly wave devices is made public on github. Is this usable?
https://github.com/QubinoHelp/Shelly_Wave_FW_OTA/

Edit: source on their website directing to the github repo: https://support.shelly.cloud/en/support/solutions/articles/103000258471-firmware-updates

**Comment by paifre** [comment]
Hello,

Firmware update for Wave 2PM is publicly available to the following URL address.
https://support.shelly.cloud/en/support/solutions/articles/103000258471-firmware-updates

Please could you make available this OTA version 11.05 to the community.
Else is there a way to proceed from a local gbl file (I know only the process from Silicon Labs which quite annoying as I have to stop everything and plug the key in PC) ?

Many thanks in advance
Best regards

**Comment by jfhautenauven** [comment]
@AlCalzone : with what is provided on their website (see link above), isn't it enough ? 
I've used the firmwares from that webpage to update both my Wave 1 and Wave 2PM modules and it works flawless :) 
I really don't know how to add this on the "upgrade funnel" via this repo, otherwise I would PR it myself, but I fear if I do so I may mess up things and cause peoples devices to have incorrect firmwares :)

**Comment by AlCalzone** [comment]
@jfhautenauven they are on it, so don't worry.

**Comment by jghaanstra** [comment]
@AlCalzone there is a pull request for this waiting to be reviewed and integrated. Could this please be added?

**Comment by AlCalzone** [comment]
I'm back from parental leave next week. Will do it then.

**Comment by AlCalzone** [comment]
Not sure if we got them all now, but the open PRs have been merged.
